// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cost_rcpp
double cost_rcpp(NumericVector x);
RcppExport SEXP _Algo_cost_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// optimal_partitioning_rcpp
IntegerVector optimal_partitioning_rcpp(NumericVector x, double beta);
RcppExport SEXP _Algo_optimal_partitioning_rcpp(SEXP xSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(optimal_partitioning_rcpp(x, beta));
    return rcpp_result_gen;
END_RCPP
}
// PELT_rcpp
IntegerVector PELT_rcpp(NumericVector x, double beta);
RcppExport SEXP _Algo_PELT_rcpp(SEXP xSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(PELT_rcpp(x, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Algo_cost_rcpp", (DL_FUNC) &_Algo_cost_rcpp, 1},
    {"_Algo_optimal_partitioning_rcpp", (DL_FUNC) &_Algo_optimal_partitioning_rcpp, 2},
    {"_Algo_PELT_rcpp", (DL_FUNC) &_Algo_PELT_rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Algo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
