# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cost_rcpp <- function(x) {
    .Call(`_Algo_cost_rcpp`, x)
}

OP_rcpp <- function(x, beta) {
    .Call(`_Algo_OP_rcpp`, x, beta)
}

PELT_rcpp <- function(x, beta) {
    .Call(`_Algo_PELT_rcpp`, x, beta)
}

