# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cost_rcpp <- function(x, changetype) {
    .Call(`_Changepoints_cost_rcpp`, x, changetype)
}

OP_rcpp <- function(x, beta, changetype) {
    .Call(`_Changepoints_OP_rcpp`, x, beta, changetype)
}

PELT_rcpp <- function(x, beta, changetype) {
    .Call(`_Changepoints_PELT_rcpp`, x, beta, changetype)
}

